version: '3'
services:
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=douyin
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=root

  minio:
    image: "minio/minio:latest"
    ports:
      - 9000:9000
      - 9001:9001
    command: server "/data" --console-address ":9001"

  redis:
    image: "redis:latest"
    ports:
      - 6379:6379

  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

#  douyin-demo-micro:
#    image: douyin-demo-micro:latest
#    depends_on:
#      - mysql
#      - minio
#      - redis
#      - Etcd
#      - jaeger
#    environment:
#      - JAEGER_DISABLED=false
#      - JAEGER_SAMPLER_TYPE=const
#      - JAEGER_SAMPLER_PARAM=1
#      - JAEGER_REPORTER_LOG_SPANS=true
#      - JAEGER_AGENT_HOST=192.168.50.144
#      - JAEGER_AGENT_PORT=6831
#    ports:
#      - "8080:8080"